name: servicesQPS
services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        ports:
            - "${MARIADB_PORT}:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./init/database.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}

    laravel:
        build:
            context: ./laravel
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8080:80"
        volumes:
            - ./volumes/app:/var/www/html/public/photos
        depends_on:
            - mariadb
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_DATABASE=${MYSQL_DATABASE}
            - DB_USERNAME=root
            - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - APP_NAME=${APP_NAME}
            - APP_ENV=${APP_ENV}
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=${APP_DEBUG}
            - APP_URL=${APP_URL}

volumes:
    db_data:
